  BaseURL = "https://Biggworks.in"
  languageCode = "en-us"
  title = "Biggworks"
  relativeURLS = true
  enableRobotsTXT = true

ignoreErrors = ["error-remote-getjson"]

[permalinks]
blog = "/blog/:year/:month/:title/"

[caches]
  [caches.getjson]
    maxAge = "30s"

[minify]
  disableHTML = true
  disableCSS = false
  disableJS = false

[params]
  description = "Your default site description"

[server]
disableLiveReload = true
