  BaseURL = "https://Biggworks.com"
  languageCode = "en-us"
  title = "Biggworks"
  disableLiveReload = true
  relativeURLS = true
  enableRobotsTXT = true
  disableHugoGeneratorInject = true

ignoreErrors = ["error-remote-getjson"]

[permalinks]
blog = "/blog/:year/:month/:title/"

[caches]
  [caches.getjson]
    maxAge = "30s"

[minify]
  disableHTML = true
  disableCSS = false
  disableJS = false
  disableXML = false
  
[params]
  description = "Your default site description"

  enableSitemap = true


