version: "3"

services:
  strapi-db:
    image: postgres
    environment:
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
      - POSTGRES_DB=strapi
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  strapi:
    image: strapi:latest
    container_name: bw-strapi
    build: ./cms
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=strapi
      - DATABASE_HOST=strapi-db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - "1337:1337"
    depends_on:
      - strapi-db
    volumes:
      - ./strapi-app:/srv/app   

  hugo:
    container_name: bw-hugo
    image: klakegg/hugo:0.101.0
    restart: always
    #network_mode: bridge
    command: server --disableLiveReload
    depends_on:
      - strapi
    ports:
      - "1313:1313"
    volumes:
      - "./hugo:/src"

  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   restart: always
  #   build:
  #     ./nginx

  #   ports:
  #     - 80:80
  #   depends_on:
  #     - hugo
  #     - strapi

volumes:
  strapi-app:
  #ghost-app:
  hugo:
