version: '3'

services:

  strapi:
    container_name: bw-strapi
    build: ./cms
    environment:    
      - NODE_ENV=production    
    ports:
      - 1337:1337

  hugo:
    container_name: bw-hugo  
    image: klakegg/hugo:0.101.0
    restart: always
    #network_mode: bridge
    command: server
    depends_on:
      - strapi
    ports:
      - "1313:1313"
    volumes:
      - "./hugo:/src"

  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   restart: always
  #   build:
  #     ./nginx

  #   ports:
  #     - 80:80
  #   depends_on:
  #     - hugo
  #     - strapi

volumes:
  #strapi-app:
  #ghost-app:
  hugo: